# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CERN.
# Copyright (C) 2025 KTH Royal Institute of Technology.

name: Publish on PyPI

on:
  workflow_call:
    inputs:
      babel-compile-catalog:
        description: 'Run Babel compile_catalog cmd'
        required: false
        default: false
        type: boolean

jobs:
  Build-N-Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Pre-install
        uses: ./.github/actions/pre-install
        if: ${{ hashFiles('.github/actions/pre-install/action.yml') != '' }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Compile catalog
        if: ${{ fromJSON(inputs.babel-compile-catalog) }}
        run: |
          python -m pip install babel
          python setup.py compile_catalog

      - name: Determine JS translation directory
        id: determine_js_path
        run: |
          PACKAGE_NAME=$(basename "$PWD" | tr '-' '_')
          THEME_PATH="$PACKAGE_NAME/theme/assets/semantic-ui/translations/$PACKAGE_NAME"
          DEFAULT_PATH="$PACKAGE_NAME/assets/semantic-ui/translations/$PACKAGE_NAME"

          if [ -f "$THEME_PATH/package.json" ]; then
            echo "Found package.json in theme path: $THEME_PATH"
            echo "translation_dir=$THEME_PATH" >> $GITHUB_OUTPUT # make path visible to subsequent steps
          elif [ -f "$DEFAULT_PATH/package.json" ]; then
            echo "Found package.json in default path: $DEFAULT_PATH"
            echo "translation_dir=$DEFAULT_PATH" >> $GITHUB_OUTPUT
          else
            echo "No JS translation directory found"
            echo "translation_dir=" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        if: ${{ steps.determine_js_path.outputs.translation_dir != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*" # latest active LTS release

      - name: Build frontend translations
        if: ${{ steps.determine_js_path.outputs.translation_dir != '' }}
        working-directory: ${{ steps.determine_js_path.outputs.translation_dir }}
        run: |
          npm ci
          npm list
          npm run compile_catalog

      - name: Build package
        run: |
          python -m build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
